# e2e setting
encoder: slowfast
slowfast_depth: 50
pretrained_model: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb_20200728-145f1097.pth

# model setting
enc_layers: 4
dec_layers: 4
dim_feedforward: 2048
# dim_feedforward: 2048
num_queries: 100
# num_queries: 100
# dropout: 0.1
dropout: 0.0
# temperature: 10000
temperature: 10000

# data setting
dataset_name: thumos14
feature: img10fps
online_slice: true
slice_len: 256
slice_overlap: 0.75
test_slice_overlap: 0.25
input_type: image

# training setting (not finialized)
lr: 0.0001
# batch_size: 8
batch_size: 4
# set_cost_class: 6
pooler_args:
   - {
       input_dim: 2048,
       base_dim: 512,
       num_layers: 6,
       output_dim: 2048
   }
   - {
       input_dim: 256,
       base_dim: 64,
       num_layers: 6,
       output_dim: 256
   }

act_reg: true
seg_refine: true
two_stage: false
mixed_selection: false
look_forward_twice: true

fix_encoder: false
fix_transform: false
pooler: twpool

img_resize: 256
img_crop_size: 224
nms_thr: 0.5

# output
output_dir: outputs/tadtr_224_twpool_condition
# output_dir: randaug/tadtr_224_m7-n4