# e2e setting
encoder: slowfast
slowfast_depth: 50
pretrained_model: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb_20200728-145f1097.pth

# model setting
enc_layers: 4
dec_layers: 4
dim_feedforward: 1024
num_queries: 40
dropout: 0.1

# data setting
dataset_name: thumos14
feature: img10fps
online_slice: true
slice_len: 256
slice_overlap: 0.75
test_slice_overlap: 0.25
input_type: image

# training setting (not finialized)
lr: 0.0001
# batch_size: 8
batch_size: 4
pooler_args:
   - {
       input_dim: 2048,
       base_dim: 512,
       num_layers: 4,
       skip: 'avg',
    #    output_dim: 2048
   }
   - {
       input_dim: 256,
       base_dim: 64,
       num_layers: 4,
       skip: 'avg',
    #    output_dim: 256
   }

fix_encoder: false
fix_transform: false
act_reg: true
pooler: twpool

img_resize: 256
img_crop_size: 224

# output
output_dir: best/tadtr_224_twpool_3