# e2e setting
encoder: video_swin
# size: tiny
# pretrained_model: https://github.com/SwinTransformer/storage/releases/download/v1.0.4/swin_tiny_patch244_window877_kinetics400_1k.pth
# size: small
# pretrained_model: https://github.com/SwinTransformer/storage/releases/download/v1.0.4/swin_small_patch244_window877_kinetics400_1k.pth
size: base
pretrained_model: https://github.com/SwinTransformer/storage/releases/download/v1.0.4/swin_base_patch244_window877_kinetics600_22k.pth

# model setting
enc_layers: 4
dec_layers: 4
# dim_feedforward: 2048
dim_feedforward: 1024
# num_queries: 100
num_queries: 40
dropout: 0.1
# dropout: 0.0
temperature: 10000
# temperature: 20

# data setting
dataset_name: thumos14
feature: img10fps
# feature: img20fps
online_slice: true
slice_len: 256
slice_overlap: 0.75
test_slice_overlap: 0.25
input_type: image

# training setting (not finialized)
lr: 0.0001
batch_size: 1

fix_encoder: false
# fix_encoder: true
fix_transform: false
# neck: simple_mixer
# lr_backbone: 0.0001
neck: identity
act_reg: true
two_stage: false
mixed_selection: false
look_forward_twice: true

# Image
# img_resize: 440
# img_crop_size: 384
# img_resize: 256
# img_crop_size: 224
# img_resize: 110
# img_crop_size: 96
img_resize: 192
img_crop_size: 168

# Training
# act_reg: false
# set_cost_class: 2
# activation: 'gelu'
rand_augment_param: rand-m7-n4-mstd0.5-inc1
# rand_augment_param: rand-m8-n3-mstd0.5-inc1

# output
output_dir: outputs/thumos14_swin_base_full_168_multi_scale_lft
# output_dir: outputs/thumos14_swin_base_identity_multi_scale_lft
