# e2e setting
encoder: slowfast
slowfast_depth: 50
pretrained_model: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb_20200728-145f1097.pth

# model setting
enc_layers: 4
dec_layers: 4
dim_feedforward: 1024
num_queries: 40
dropout: 0.1

# data setting
dataset_name: thumos14
feature: img10fps
online_slice: true
slice_len: 256
slice_overlap: 0.75
test_slice_overlap: 0.25
input_type: image

# training setting (not finialized)
lr: 0.0001
batch_size: 2

fix_encoder: false
# fix_encoder: true
fix_transform: false
# neck: pyramid
neck: identity
lr_backbone: 0.00001

# Image
# img_resize: 440
# img_crop_size: 384
img_resize: 110
img_crop_size: 96
# img_resize: 256
# img_crop_size: 224

# Training
# act_reg: false
# set_cost_class: 2
# activation: 'gelu'
rand_augment_param: rand-m8-n3-mstd0.5-inc1

# output
output_dir: outputs/thumos14_e2e_slowfast_test___

