# e2e setting
encoder: video_swin
size: tiny
pretrained_model: https://github.com/SwinTransformer/storage/releases/download/v1.0.4/swin_tiny_patch244_window877_kinetics400_1k.pth

# model setting
enc_layers: 4
dec_layers: 4
# dim_feedforward: 2048
dim_feedforward: 1024
num_queries: 40
dropout: 0.1
# temperature: 10000
temperature: 20

# data setting
dataset_name: thumos14
feature: img10fps
online_slice: true
slice_len: 256
slice_overlap: 0.75
test_slice_overlap: 0.25
input_type: image

# training setting (not finialized)
lr: 0.0001
batch_size: 4

fix_encoder: false
# fix_encoder: false
fix_transform: false
# neck: pyramid
lr_backbone: 0.00001
neck: identity


# Image
# img_resize: 440
img_resize: 256
# img_resize: 110
# img_crop_size: 384
img_crop_size: 224
# img_crop_size: 96

# Training
# act_reg: false
# set_cost_class: 2
# activation: 'gelu'
# rand_augment_param: rand-m7-n4-mstd0.5-inc1
rand_augment_param: rand-m8-n3-mstd0.5-inc1

# output
output_dir: outputs/thumos14_swin
